# github workflow for running django test on backend/

name: backend CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Change Directory to backend
      run: |
        cd backend
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        pip-flags: "--no-cache-dir"
    - name: Install Requirements
      run: pip install -r requirements.txt
    - name: Run Migration
      run: python manage.py migrate
    - name: Run Tests
      run: python manage.py test

